version: 1
type: go
resolver:
  snapshotRepo: go_repo_key
  releaseRepo: go_repo_key
  serverID: Default-Server
deployer:
  snapshotRepo: go_repo_key
  releaseRepo: go_repo_key
  serverID: Default-Server

